apiVersion: v1
kind: Secret
metadata:
  name: helloworld-signature-secret
  annotations:
    argocd.interlace.dev/signature-resource: "true"
    argocd.interlace.dev/signature-compress: "true"
type: Opaque
